import argparse
import os, sys
from gmusicapi import  Mobileclient

parser = argparse.ArgumentParser()
parser.add_argument("-s", "--songlist", help="filename containing artists/songs, one per line", type=str)
parser.add_argument("-p", "--playlist", help="name of playlist to add", type=str)
args = parser.parse_args()


if not args.playlist or not args.songlist:
    parser.print_help()
    sys.exit(-1)

print("Using %s as a song list\n" % args.songlist)
if not os.path.exists(args.songlist):
    print("Can't find %s. Aborting")
    sys.exit(-2)


mc = Mobileclient()
if not mc.oauth_login(Mobileclient.FROM_MAC_ADDRESS):
  mc.perform_oauth()

playlists=mc.get_all_playlists()
playlist_id = None
for p in playlists:
    if p['name'] == args.playlist:
        playlist_id = p['id']
        print("found existing playlist %s, id %s" % (args.playlist, playlist_id))
        break

if not playlist_id:
    print("Couldn't find a playlist called %s, creating..." % args.playlist, end = '')
    playlist_id = mc.create_playlist(args.playlist, "autogenerated by John's playlist maker")
    print("done. id:%s\n" % playlist_id)

with open(args.songlist, 'rb') as songlist:
  try:
    names=songlist.readlines()
  except e:
      print("Couldn't read from the songlist: %s\n" % e)
      sys.exit(-1)

store_ids = []
for name in names:
    name = name.strip()
    print("Searching for %s.." % name, end = '')
    try:
      track = mc.search(name)['song_hits'][0]['track']
    except IndexError:
        print(".. not found")
        continue
    artist = track['artist']
    title =  track['title']
    try:
      year   = track['year']
    except KeyError:
      year   = "????"
    print("..found %s/%s from %s" % (artist, title, year))
    store_ids.append(track['storeId'])

print("found %d songs in %s" % (len(store_ids), args.songlist))
mc.add_songs_to_playlist(playlist_id, store_ids)

sys.exit(0)


x['song_hits'][0]

# {
#   'type': '1',
#   'track': {
#      'kind': 'sj#track',
#      'title': 'A Little Respect (2009 Remastered Version)',
#      'artist': 'Erasure',
#      'composer': '',
#      'album': 'The Innocents',
#      'albumArtist': 'Erasure',
#      'year': 1988,
#      'trackNumber': 1,
#      'genre': 'Pop',
#      'durationMillis': '213000',
#      'albumArtRef': [{
#         'kind': 'sj#imageRef',
#         'url': 'http://lh3.googleusercontent.com/Tf9GXGZPbTJ53JWXp6o7WIysqlFzuK9IH0Xp7fjSPRBc9nZkqDnANViirYWNxu1EqeuifAPsdII',
#         'aspectRatio': '1',
#         'autogen': False
#       }],
#       'discNumber': 1,
#       'estimatedSize': '8561921',
#       'trackType': '7',
#       'storeId': 'Thddlbjshhhwtbpatg36kk4pv5y',
#       'albumId': 'dqattbyd4ex5dsoeb5tzqtqioa',
#       'artistId': ['rtsic7c3ie2v425hygkupwd44m'],
#       'nid': 'hddlbjshhhwtbpatg36kk4pv5y',
#       'trackAvailableForSubscription': True,
#       'trackAvailableForPurchase': True,
#       'albumAvailableForPurchase': True,
#       'explicitType': '2'},
#       'cluster': [{
#         'type': '1',
#         'category': '1',
#         'id': 'search_track'
#       }]
# }

